### ISSUE TITLE
数据集中一个小小的bug

### ISSUE THREAD

**Issue by init-neok** [less-and-less-bugs/LogicMD#2]
您好，首先非常感觉作者提供如此详尽可读性强的代码，我在复现过程中遇到了一个小问题，您在dataset.py中31行` img_path='/home/zkn/code/beachmark_datasets/LogicDM/dataset/twitter/embedding34.pt', max_length=150, mode`引入的embedding34.pt的在进行imageEncoder时报错，具体情况为RuntimeError: mat1 and mat2 shapes cannot be multiplied (1568x512 and 768x500) 我看了代码可能是embedding34.pt的问题，看了jupyter脚本没找到对应的生成这个pt文件的部分，因为我不太熟悉原生的数据集，不知道您能否抽空fix一下。

**Comment by init-neok** [comment]
哦我自己解决了，改用数据集文件里的embedding.pt就好

**Comment by less-and-less-bugs** [comment]
谢谢关注！

因为这个工作在今年1月份就已经完成，我不清楚我给出的Readme文件是否完全。如果你可以成功复现，是否可以在issue里分享运行文档，方便其他研究者参考？

祝好！

Neok ***@***.***> 于2023年9月5日周二 09:52写道：

**Comment by init-neok** [comment]
> 

好的，确实有些不太完整。不过已经非常清楚了，如果是做虚假检测的同方向的人的话相信跑起来并不会多费劲儿，过几天等我把代码理一遍我来给出一个详细的readme文件来介绍一下吧，还是谢谢原作者能够提供如此详细的代码了！您的共享为我的研究给出了非常好的借鉴作用！

**Comment by less-and-less-bugs** [comment]
非常感谢。希望这个项目可以帮助到你。

Best Regard！
Hui

Neok ***@***.***> 于2023年9月5日周二 16:45写道：

**Comment by Amyjiang98** [comment]
你好，谢谢作者开源代码！也谢谢init-neok分享bug的解决办法，我在复现过程中也遇到了同样的问题，改了shape之后可以运行但没有达到论文中的效果，想问问init-neok是否成功复现了，可以分享一下readme吗？非常感谢！
